---
version: "2"
services:
  homer:
    # image: jez500/bender
    #To build from source, comment previous line and uncomment below
    build: .
    container_name: homer
    volumes:
      - /your/local/assets/:/app/static
    ports:
      - 8080:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
